"""init tables

Revision ID: d3e89c402e4c
Revises: 
Create Date: 2026-09-04 20:58:54.441088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e89c402e4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('part_id', sa.String(length=100), nullable=False),
    sa.Column('part_weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_name'), 'spare_parts', ['name'], unique=False)
    op.create_index(op.f('ix_spare_parts_part_id'), 'spare_parts', ['part_id'], unique=True)
    op.create_index(op.f('ix_spare_parts_sku'), 'spare_parts', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spare_parts_sku'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_part_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_name'), table_name='spare_parts')
    op.drop_table('spare_parts')
    # ### end Alembic commands ###
